version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - redis

  redis:
    image: redis:6.2.6-alpine3.14
